config/routes.rb
Beersquare::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|es/ do

    match '/profile' => 'profile#show'

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    resources :breweries
    resources :beers
    match '/beers/like/:id' => 'beers#like'
    match '/beers/unlike/:id' => 'beers#unlike'
    match '/beers/check/:id' => 'beers#check'
    match '/beers/uncheck/:id' => 'beers#uncheck'
    match '/checklist' => 'profile#checklist'
    match '/' => 'home#index'

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end

    devise_scope :user do
      get "sign_in", :to => "devise/sessions#new"
      get "login", :to => "devise/sessions#new"
    end
    
    root :to => 'home#index'
  end

end

app/views/shared/_beer.html.erb
<div class="beer-wrapper">
  <div class="beer beer_<%= beer.id %>">
    
    <div class="check <%= 'hidden' unless current_user_checks_beer(beer) %>"></div>
    
    <div class="beer-hover">
      <div class="button-wrapper">
                
        <div class="checked-buttons <%= 'hidden' unless current_user_checks_beer(beer) %>">
          <div class="button primary"><%= t'common.checked' %></div>
          <%= link_to t('common.uncheck'), {:controller => "beers", :action => "uncheck", :id => beer.id}, :data => {:remote => 'true'}, :class => 'button red' %>
        </div> <!-- user_checks_beer -->
        <div class="unchecked-buttons <%= 'hidden' if current_user_checks_beer(beer) %>">
          <%= link_to t('common.check'), {:controller => "beers", :action => "check", :id => beer.id}, :data => {:remote => 'true'}, :class => 'button primary' %>
        </div>
        
      </div> <!-- button_wrapper -->
      
      <div class="button-wrapper">
        <%= link_to t('common.view'), beer, :class => 'button secondary' %>
      </div> <!-- button_wrapper -->
      
    </div> <!-- .beer-hover -->
    
    
    <div class="name">
      <% if beer_country(beer) %>
        <div class="flag flag-<%= beer_country(beer).downcase %>"></div>
      <% end %>
      <%= beer.name %>
    </div>
    <div class="brewery"><%= beer.brewery.name unless beer.brewery.blank? %></div>
    <%= image_tag beer.photo.url(:small) %>
    
    <div>Le gusta a <%= beer.total_likes %></div>
    <div>La han probado <%= beer.total_checks %></div>
  </div> <!-- beer -->
</div> <!-- beer_wrapper -->

app/views/shared/_footer.html.erb
<div id="footer">
 <div class="container">

  <div class="footer-top">
    <div class="pull-right">
      <%= link_to "Español", params.merge({:locale => :es}) %>
       |
      <%= link_to "English", params.merge({:locale => :en}) %>
    </div>
    
    <div class="copyright">
      Birralist &copy; 2013
    </div>
  </div>

  <div class="footer-bottom">
    <div class=" copy pull-right">
      Creado con <span class="coffee"></span> y <span class="heart"></span> en Madrid <a href="http://www.pappyrus.es" target="_blank"><span class="logo_pappyrus"></span>Pappyrus web</a>
    </div>
    
    <ul>
      <li>Aviso legal</li>
      <li>Contacto</li>
    </ul>
    
  </div>
   
 </div><!-- .container -->
</div><!-- #footer -->

app/views/shared/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      
      <div class="user_menu pull-right">
        <% if user_signed_in? %>
          <span><%= t 'common.hello' %> <%= current_user.username %></span> |
          <%= link_to t('common.profile'), profile_path %> |
          <%= link_to t('common.logout'), destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to t('common.login'), new_user_session_path %>
        <% end %>
      </div>
      
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <%= link_to 'Beersquare', root_path, :class => 'brand', :title => 'Home' %>
        <ul class="nav">
          <li class="<%= 'active' if params[:controller] == 'beers' %>"><%= link_to t('common.beers'), beers_path %></li>
          <li class="<%= 'active' if params[:controller] == 'breweries' %>"><%= link_to t('common.breweries'), breweries_path %></li>
          <li class="<%= 'active' if params[:controller] == 'profile' && params[:action] == 'checklist' %>"><%= link_to t('common.checklist'), :controller => "/profile", :action => "checklist" %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div> <!-- .container -->
  </div> <!-- .navbar-inner -->
</div> <!-- .navbar -->