config/routes.rb
Beersquare::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|es/ do

    match '/profile' => 'profile#show'

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    resources :breweries
    resources :beers
    match '/beers/like/:id' => 'beers#like'
    match '/beers/unlike/:id' => 'beers#unlike'
    match '/beers/check/:id' => 'beers#check'
    match '/beers/uncheck/:id' => 'beers#uncheck'
    match '/checklist' => 'profile#checklist'
    match '/' => 'home#index'

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end

    devise_scope :user do
      get "sign_in", :to => "devise/sessions#new"
      get "login", :to => "devise/sessions#new"
    end
    
    root :to => 'home#index'
  end

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  extend Geocoder::Model::ActiveRecord
  has_many :beers, :dependent => :destroy

  attr_accessible :name, :country, :latitude, :longitude, :state, :city, :address, :zip_code, :photo

  #Maps
  geocoded_by :full_address
  after_validation :geocode

  def full_address
    self.name+' '+(self.address||'')+' '+(self.city||'')+' '+(self.zip_code||'')+' '+(self.state||'')
  end

  #Images
  has_attached_file :photo,
                    :styles => { :medium => "940x240", :small => "150x150>" },
                    :default_url =>  'brewery.jpeg',
                    :url  => "/assets/breweries/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/breweries/:id/:style/:basename.:extension"

  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @filter_breweries = Brewery.order(:name).where("name like ?", "%#{params[:term]}%")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @breweries }
      format.js { render json: @filter_breweries.map(&:name)}
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    @brewery = Brewery.find(params[:id])
    @beers = @brewery.beers

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @brewery }
    end
  end

  # GET /breweries/new
  # GET /breweries/new.json
  def new
    @brewery = Brewery.new
    @countries = Country.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @brewery }
    end
  end

  # GET /breweries/1/edit
  def edit
    @brewery = Brewery.find(params[:id])
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(params[:brewery])

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, :notice => 'Brewery was successfully created.' }
        format.json { render :json => @brewery, :status => :created, :location => @brewery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @brewery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /breweries/1
  # PUT /breweries/1.json
  def update
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      if @brewery.update_attributes(params[:brewery])
        format.html { redirect_to @brewery, :notice => 'Brewery was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @brewery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <fieldset>
    <% if @brewery.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>
      <ul>
        <% @brewery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :country %>
    <%= select("brewery", "country", Country.all {|c| [ c[0], c[1] ] }, {:include_blank => 'Select'}) %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>

    <%= f.label :photo %>
    <%= f.file_field :photo %>

    <div class="form-actions">
      <div class="pull-right">
        <%= f.submit :class => 'btn btn-primary'%>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/breweries/edit.html.erb
<h3>Editing brewery</h3>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<div class="brewery">
  <h1>
    <%= link_to t('.add_brewery'), new_brewery_path, :class => 'button primary pull-right' %>
    <%= t '.title' %>
  </h1>

  <ul>
  <% @breweries.each do |brewery| %>
    <li>
      <%= link_to brewery.name, brewery %> (<%= brewery.country %>)
    </li>

    <!-- <tr>
      <td><%= brewery.name %></td>
      <td><%= brewery.country %></td>
      <td><%= link_to 'Show', brewery %></td>
      <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
      <td><%= link_to 'Destroy', brewery, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr> -->
  <% end %>
  </ul>
</div>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<input type="hidden" value="<%= @brewery.latitude %>" id="brew_lat"/>
<input type="hidden" value="<%= @brewery.longitude %>" id="brew_lgt"/>


<div class="brewery row-fluid">
  
  <%= link_to t('common.edit'), edit_brewery_path(@brewery), :class => 'button primary pull-right' %>
  <h1><div class="flag flag-<%= @brewery.country.downcase %>"></div><%= @brewery.name %></h1>

  <div class="brewery-cover row-fluid">
    <%= image_tag @brewery.photo.url(:medium) %>
  </div>

  <div class="row-fluid brewery-info">
    <div class="span6 ">
      <div class="form-inline">
        <div class="row-fluid">
          <div class="span6"><span class="label-right"><%= t('common.address') %></span></div>
          <div class="span6"><span><%= @brewery.address %></span></div>
        </div>
        <div class="row-fluid">
          <div class="span6"><span class="label-right"><%= t('.city') %></span></div>
          <div class="span6"><span><%= @brewery.city %></span></div>
        </div>
        <div class="row-fluid">
          <div class="span6"><span class="label-right"><%= t('.state') %></span></div>
          <div class="span6"><span><%= @brewery.state %></span></div>
        </div>
        <div class="row-fluid">
          <div class="span6"><span class="label-right"><%= t('.country') %></span></div>
          <div class="span6"><span><%= @brewery.country %></span></div>
        </div>
      </div>
    </div>
    <div class="span6">
      <div class="hide" id="brew_map" style="width:100%; height:300px;"></div>
    </div>
  </div>

  <h2>Cervezas de esta marca:</h2>
  <div class="beer-list">
    <% unless @beers.blank? %>
      <%= render :partial => 'shared/beer', :collection => @beers %>
    <% else %>
      <div class="blank">
        <div class="title">
          <%= t'.no_beers' %>
        </div>
        <p>
          <%= t'.blank_text'%> <%= link_to t('common.add_beer'), new_beer_path %>
        </p>
      </div> <!-- .blank -->
    <% end %>
  </div> <!-- .beer_list -->

</div>