config/routes.rb
Beersquare::Application.routes.draw do

  

  scope "(:locale)", :locale => /en|es/ do

    match '/profile' => 'profile#show'

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    resources :breweries
    resources :beers
    match '/beers/like/:id' => 'beers#like'
    match '/beers/unlike/:id' => 'beers#unlike'
    match '/beers/check/:id' => 'beers#check'
    match '/beers/uncheck/:id' => 'beers#uncheck'
    match '/checklist' => 'profile#checklist'
    match '/' => 'home#index'

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end

    devise_scope :user do
      get "sign_in", :to => "devise/sessions#new"
      get "login", :to => "devise/sessions#new"
    end
    
    root :to => 'home#index'
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  has_one :user
  
  # User likes beers
  has_many :likes
  has_many :checks
  has_many :likes_users, :through => :likes, :source => :user
  has_many :checks_users, :through => :checks, :source => :user
  #has_and_belongs_to_many :users


  #Images
  has_attached_file :photo, :styles => { :small => "150x150>", :medium => "300x300>" },
                    :url  => "/assets/beers/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/beers/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  def total_likes
    self.likes_users.count
  end

  def total_checks
    self.checks_users.count
  end

  #
  #Virtual properties
  #

  #Brewery_Name
  def brewery_name
    brewery.try(:name)
  end

  def brewery_name=(name)
    self.brewery = Brewery.find_or_create_by_name(name) if name.present?
  end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.json
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
    @brewery_items = Brewery.all.map(&:name)
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(params[:beer])
    @beer.user_id = current_user.id if user_signed_in?

#    UserMailer.new_beer().deliver

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, :notice => 'Beer was successfully created.' }
        format.json { render :json => @beer, :status => :created, :location => @beer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @beer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.json
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to @beer, :notice => 'Beer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @beer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :ok }
    end
  end
  
  def like
    if user_signed_in?
      @beer = Beer.find(params[:id])
      current_user.likes_beers << @beer unless current_user.likes_beers.exists?(@beer.id)
      respond_to do |format|
        format.html { redirect_to beers_path }
        format.js
      end
    else
      redirect_to :controller => 'devise/sessions', :action => "new"
    end
  end
  
  def unlike
    if user_signed_in?
      @beer = Beer.find(params[:id])
      current_user.likes_beers.delete(@beer) if current_user.likes_beers.exists?(@beer.id)
      respond_to do |format|
        format.html { redirect_to beers_path }
        format.js
      end
    else
      redirect_to :controller => 'devise/sessions', :action => "new"
    end
  end
  
  def check
    if user_signed_in?
      @beer = Beer.find(params[:id])
      current_user.checks_beers << @beer unless current_user.checks_beers.exists?(@beer.id)
      #flash[:notice] = 'Beer checked!'
      #redirect_to :action => "show", :id => @beer.id
      respond_to do |format|
        format.html { redirect_to beers_path }
        format.js
      end
    else
      redirect_to :controller => 'devise/sessions', :action => "new"
    end
    
  end

  def uncheck
    if user_signed_in?
      @beer = Beer.find(params[:id])
      current_user.checks_beers.delete(@beer) if current_user.checks_beers.exists?(@beer.id)
      #redirect_to :action => "show", :id => @beer.id
      respond_to do |format|
        format.html { redirect_to beers_path }
        format.js
      end
    else
      redirect_to :controller => 'devise/sessions', :action => "new"
    end
  end
  
end

app/helpers/beers_helper.rb
module BeersHelper
  
  def total_beers
    Beer.count
  end
  
  def beer_country(beer)
    if !beer.country.blank?
      beer.country.downcase
    elsif beer.brewery && !beer.brewery.country.blank?
      beer.brewery.country.downcase
    end
  end
  
  def current_user_likes_beer(beer)
    current_user.likes_beers.exists?(beer.id) if user_signed_in?
  end
  
  def current_user_checks_beer(beer)
    current_user.checks_beers.exists?(beer.id) if user_signed_in?
  end
  
  def current_user_total_countries
    current_user.checks_beers.select(:country).uniq(&:country).count
  end
  
  def current_user_total_added_beers
    Beer.where(:user_id => current_user.id).count
  end
  
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brewery_name %><br />
    <%= f.text_field :brewery_name, data: {autocomplete_source: '/breweries.js' } %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= select("beer", "country", Country.all {|c| [ c[0], c[1] ] }, {:include_blank => 'Select'}) %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="form-actions">
    <%= f.submit :class=>'btn btn-primary pull-right'%>
  </div>
<% end %>

app/views/beers/check.js.erb
$('.beer_<%= @beer.id %> .check').removeClass('hidden');
// $('.notice-wrapper .notice').html('Beer checked').fadeIn().delay(5000).fadeOut();
$('.beer_<%= @beer.id %> .checked-buttons').removeClass('hidden');
$('.beer_<%= @beer.id %> .unchecked-buttons').addClass('hidden');

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<div class="beer">
  <h1>
    <%= link_to t('.add_beer'), new_beer_path, :class => 'button primary pull-right' %>
    <%= t '.title' %>
  </h1>

  <div class="beer-list">
    <%= render :partial => 'shared/beer', :collection => @beers %>
  </div>
</div> <!-- .beer -->

app/views/beers/like.js.erb
$('.beer_<%= @beer.id %> .liked-buttons').removeClass('hidden');
$('.beer_<%= @beer.id %> .unliked-buttons').addClass('hidden');

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<div class="beer beer_<%= @beer.id %> row-fluid">
  
  <div class="span8">
    <h1>
      <% if beer_country(@beer) %>
        <div class="flag flag-<%= beer_country(@beer).downcase %>"></div>
      <% end %>
      <%= @beer.name %>
    </h1>
    
    <% unless @beer.brewery.blank? -%>
      <div class="brewery"><%= link_to @beer.brewery.name, @beer.brewery %></div>
    <% end -%>
    
    <div class="button-wrapper">
      
      <div class="checked-buttons <%= 'hidden' unless current_user_checks_beer(@beer) %>">
        <div class="button primary"><%= t'common.checked' %></div>
        <%= link_to t('common.uncheck'), {:controller => "beers", :action => "uncheck", :id => @beer.id}, :data => {:remote => 'true'}, :class => 'button red' %>
      </div> <!-- user_checks_beer -->
      <div class="unchecked-buttons <%= 'hidden' if current_user_checks_beer(@beer) %>">
        <%= link_to t('common.check'), {:controller => "beers", :action => "check", :id => @beer.id}, :data => {:remote => 'true'}, :class => 'button primary' %>
      </div>
      
    </div> <!-- button_wrapper -->
     
    <div class="button-wrapper">
      <div class="liked-buttons <%= 'hidden' unless current_user_likes_beer(@beer) %>">
        <div class="button secondary"><%= t'common.liked' %></div>
        <%= link_to t('common.unlike'), {:controller => "beers", :action => "unlike", :id => @beer.id}, :data => {:remote => 'true'}, :class => 'button red' %>
      </div> <!-- user_checks_beer -->
      <div class="unliked-buttons <%= 'hidden' if current_user_likes_beer(@beer) %>">
        <%= link_to t('common.like'), {:controller => "beers", :action => "like", :id => @beer.id}, :data => {:remote => 'true'}, :class => 'button secondary' %>
      </div>

    </div> <!-- button_wrapper -->
    
    <div class="row-fluid beer-info">
      <div class="span6 ">
        <div class="form-inline">
          <div class="row-fluid">
            <div class="span6"><span class="label-right"><%= t('.country') %></span></div>
            <div class="span6"><span><%= @beer.country %></span></div>
          </div>
          <div class="row-fluid">
            <div class="span6"><span class="label-right"><%= t('.description') %></span></div>
            <div class="span6"><span><%= @beer.description %></span></div>
          </div>
        </div>
      </div>
    </div> <!-- beer-info -->
    
    
  </div> <!-- span8 -->
  
  <div class="span4">
    <div class="images-wrapper">
    <% if current_user_checks_beer(@beer) -%>
      <div class="check"></div>
    <% end -%>
    
    <%= image_tag @beer.photo.url(:medium) %>
    </div><!-- images-wrapper -->
  </div> <!-- span4 -->
  
</div><!-- row -->




<%= link_to 'Edit', edit_beer_path(@beer) %>

app/views/beers/uncheck.js.erb
$('.beer_<%= @beer.id %> .check').addClass('hidden');
// $('.notice-wrapper .notice').html('Beer checked').fadeIn().delay(5000).fadeOut();
$('.beer_<%= @beer.id %> .checked-buttons').addClass('hidden');
$('.beer_<%= @beer.id %> .unchecked-buttons').removeClass('hidden');

app/views/beers/unlike.js.erb
$('.beer_<%= @beer.id %> .liked-buttons').addClass('hidden');
$('.beer_<%= @beer.id %> .unliked-buttons').removeClass('hidden');